# Generated by Django 4.2.1 on 2023-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
