# Generated by Django 4.2.1 on 2023-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_click_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='ip_routable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
